<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>HenikenERP.Data</AssemblyName>
    <RootNamespace>HenikenERP.Data</RootNamespace>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySql.Data" Version="8.0.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HenikenERP.Core\HenikenERP.Core.csproj" />
    <ProjectReference Include="..\HenikenERP.Common\HenikenERP.Common.csproj" />
  </ItemGroup>
</Project>

